apiVersion: apps/v2
kind: Deployment
metadata:
  name: nodeapp
  labels:
    app: node
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node
      version: v2
  template:
    metadata:
      labels:
        app: node
        version: v2
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "nodeapp"
        dapr.io/app-port: "3000"
    spec:
      containers:
      - name: node
        image: limingyu007/dapr-istio/nodeapp:v2
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
